// <auto-generated />
using EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Services.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180317161629_Manicure_CosmeticService")]
    partial class Manicure_CosmeticService
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.CosmeticService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nameservice");

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.ToTable("CosmeticServices");
                });

            modelBuilder.Entity("Models.HairdresserService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nameservice");

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.ToTable("HairdresserServices");
                });

            modelBuilder.Entity("Models.Manicure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nameservice");

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.ToTable("Manicures");
                });
#pragma warning restore 612, 618
        }
    }
}
